name: GitHub Actions Continuous Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup Pages
      uses: actions/configure-pages@v1
    - uses: actions/setup-node@master
      with:
        node-version: '16.x'
    - run: npm ci
    - run: npm run build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: './build'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@main
